import React from 'react';
import { connect } from 'react-redux';
import { Button, Platform, StyleSheet, View } from 'react-native';
import NoteList from '../components/NoteList';
import ActionButton from 'react-native-action-button';
import actions from '../redux/actions';
import theme from '../theme';
import uuid from 'uuid';

const styles = StyleSheet.create({
    addItemButton: {
        fontSize: 28
    },
    container: {
        backgroundColor: 'white',
        flex: 1
    }
});

/**
 * The Home Screen - this is a container component built on top of
 * the React Navigation system that is fed the list of notes to be
 * displayed
 * 
 * @class Home
 * @extends {React.Component}
 */
class Home extends React.Component {
    /**
     * Options for react-navigation
     * 
     * @static
     * @memberof Home
     */
    static navigationOptions = ({ navigation, screenProps }) => {
        const baseOptions = { title: 'Notes' };

        if (Platform.OS === 'ios') {
            const buttonHandler = () => {
                const { navigate } = navigation;
                navigate('Details', { noteId: uuid.v4() });
            };

            return {
                ...baseOptions,
                headerRight: <Button title="+" onPress={buttonHandler} />
            }
        } else {
            return {
                ...baseOptions,
                headerStyle: {
                    marginTop: 20,
                    backgroundColor: theme.headerBackgroundColor
                },
                headerTintColor: theme.headerForegroundColor
            };
        }
    };

    /**
     * Event handler called when a user tries to press a note. 
     * 
     * @param {String} noteId the id of the note to be selected
     * @memberof Home
     */
    onViewNote(item) {
        const { navigate } = this.props.navigation;
        navigate('Details', { noteId: item.noteId });
    }

    /**
     * Event handler called when a user tries to delete a note. 
     * 
     * @param {String} noteId the id of the note to be deleted
     * @memberof Home
     */
    onDeleteNote(item) {
        this.props.deleteNote(item.noteId);
    }

    /**
     * Event handler called when a user tries to add a note
     * 
     * @memberof Home
     */
    onAddNote() {
        const { navigate } = this.props.navigation;
        navigate('Details', { noteId: uuid.v4() });
    }

    /**
     * Part of the React lifecycle that actually renders the component.
     * 
     * @returns {JSX.Element} a component tree rendered in JSX
     * @memberof Home
     */
    render() {
        // Sometimes, the parameters we feed to the JSX components get
        // unwieldly; we can provide objects instead - this is the props
        // fed to the NoteList component.
        const noteListParams = {
            notes: this.props.notes,
            onViewNote: (item) => this.onViewNote(item),
            onDeleteNote: (item) => this.onDeleteNote(item)
        };

        const actionButtonParams = {
            buttonColor: theme.actionButtonColor,
            onPress: () => this.onAddNote()
        };

        // The rendered component.  Note that if we are on iOS, the Add Item
        // component is rendered in the header.  If we are on Android, then 
        // the Add Item component is rendered as a floating action button on
        // the page.
        return (
            <View style={styles.container}>
                <NoteList {...noteListParams} />
                {(Platform.OS === 'android') && <ActionButton {...actionButtonParams} />}
            </View>
        );
    }
}

/**
 * Maps the redux store state to properties required by this container
 * component.  In this case, we only want to see the records that are
 * not deleted.
 * 
 * @param {Object} state the redux store state
 */
const mapStateToProps = (state) => {
    return {
        notes: state.notes.filter(n => !n.isDeleted)
    };
};

/**
 * Maps the dispatch method to dispatch the appropriate actions based
 * on the events that will be generated by this container component.
 * 
 * @param {Function} dispatch the dispatcher from redux
 */
const mapDispatchToProps = (dispatch) => {
    return {
        deleteNote: (noteId) => dispatch(actions.notes.deleteNote({ noteId }))
    };
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
